### ISSUE TITLE
ERROR NullInjectorError:

### ISSUE THREAD

**Issue by henning410** [rodrigokamada/angular-recaptcha-v2#1]
ERROR NullInjectorError: R3InjectorError(AppModule)[ReCaptchaService -> ReCaptchaService -> ReCaptchaService]: 
  NullInjectorError: No provider for ReCaptchaService!
  
  you need also as provider: ReCaptchaService

**Comment by rodrigokamada** [comment]
Hi @henning410 ,

Have you made the settings in your module? You need to configure the `RecaptchaFormsModule` and `RecaptchaModule` modules.

**Comment by henning410** [comment]
Hey @rodrigokamada 

sorry for the late answer. Yes, I configured both modules. The only solution to get it working for me was using `ReCaptchaService` as provider
